owner: gegi-status
repo: gegi-status.github.io
user-agent: mdaoustudes

skipTopicsUpdate: true

sites:
  - name: UdeS website (prod)
    url: https://www.usherbrooke.ca/
    icon: https://www.usherbrooke.ca/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 800
  - name: Faculté génie website (prod)
    url: https://www.usherbrooke.ca/genie/
    expectedStatusCodes:
      - 200
    maxResponseTime: 800
  - name: Faculté génie (intranet)
    url: https://usherbrooke.sharepoint.com/sites/fgen
    expectedStatusCodes:
      - 200
      - 403 #Forbidden (Authentication redirect)
    maxResponseTime: 800
  - name: Département GEGI website (prod)
    url: https://www.usherbrooke.ca/genie-electrique-informatique/
    expectedStatusCodes:
      - 200
    maxResponseTime: 800
  - name: Département GEGI (intranet)
    url: https://www.usherbrooke.ca/intranet-genie-electrique-informatique/
    expectedStatusCodes:
      - 200
    maxResponseTime: 800

  - name: Calendrier facultaire (prod)
    url: https://www.gegi.usherbrooke.ca/calendrier-facultaire/
    expectedStatusCodes:
      - 200
    maxResponseTime: 800
  - name: Horarius (prod)
    url: https://www.gegi.usherbrooke.ca/horarius/
    expectedStatusCodes:
      - 200
      - 400 #(Authentication redirect)
    maxResponseTime: 800
  - name: Réservation (prod)
    url: https://www.gegi.usherbrooke.ca/reservation/
    expectedStatusCodes:
      - 200
      - 400 #(Authentication redirect)
    maxResponseTime: 800

assignees:
  - mdaoustudes

status-website:
  cname: gegi-status.github.io
  logoUrl: https://www.usherbrooke.ca/res/fileadmin/logo/UdeS_blanc.png
  name: GEGI status
  introTitle: "Status page for GEGI related websites"
  theme: dark
  navbar:
    - title: UdeS status
      href: https://etatdesservices.usherbrooke.ca/

i18n:
  footer: This page is [open source]($REPO)

workflowSchedule:
  graphs: "0 0 * * *" #At 00:00.
  responseTime: "0 1-23/2 * * *" #At every 2 hours past 01:00.
  staticSite: "0 1 * * *" #At 01:00.
  summary: "0 0 * * *" #At 00:00.
  updateTemplate: "0 0 * * *" #At 00:00.
  updates: "0 3 * * *" #At 03:00.
  uptime: "*/5 * * * *" #At every 5th minute.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
